### ISSUE TITLE
Версионирование

### ISSUE THREAD

**Issue by Nalorokk** [AlexGyver/GyverLamp2#1]
Было бы не плохо со второго раза уже нормально помечать версии git тегами, а не подпапками типо firmware/x.y.z. У способа с подпапками одни минусы, никто так не работает. Главный из которых - сложно нормально отследить diff между ревизиями прошивки. Потенциальные сложности при мердже пулл реквестов. Зачем так делать вообще? Еще и второй раз подряд те же грабли.

**Comment by AlexGyver** [comment]
Я использую гит как облачное хранилище, не более. Не вижу где тут грабли и всё такое

**Comment by AlexGyver** [comment]
Могу специально для тебя сделать папку dev и не менять ее название. Но где там указывать версию и как "сообщить" об обновлении?

**Comment by Nalorokk** [comment]
Чтобы все делать правильно следует разрабатывать прошивку так чтобы основной файл с setup {} был например в firmware/GyverLamp2.ino. 

Почему так будет лучше? Потому что большинство тех кто собирает лампу делает все таки какие-то модификации для себя, и у них отличная версия. Если делать так как я пишу они смогут обновить свою сборку прошивки просто сделав git pull. Git сам сможет в большинстве случаев применить обновление к коду прошивки, не потеряв изменения которые внес для себя человек. Так же это упростит людям вообще сравнение версий и даст просто понимание насколько они вообще заинтересованы в обновлении. Это на самом деле удобный инструмент, я советую его изучить, думаю он тебе понравится. Это правда удобно.

Как отмечать версии? Просто командой "git tag v0.9" после "git commit".  github удобно и понятно это покажет. 
Прошу, изучи инструмент с которым работаешь :)

Если будут вопросы, можешь написать мне: tg @Nalorokk к примеру.

На мой взгляд вообще круто было бы все таки совместно разрабатывать прошивку именно в одном гите, все таки именно для этого он сделан, я понимаю что в этом конечно есть и минусы, но если правильно сформулировать цели проекта и правила для слияний, можно сделать прошивку гораздо лучше, совместными усилиями. Вот эти 10 версий первого варианта прошивки это ведь правда не удобно. Нет какой-то "ultimate" версии. А могла бы быть, средства разработки вполне позволяют сделать все круто.

**Comment by AlexGyver** [comment]
Какая команда git commit? Я не работаю в консоли, и не буду)
setup() и так в главной вкладке
10 версий первой прошивки - они уже не версии, а самостоятельные проекты

**Comment by Nalorokk** [comment]
К git существует много разных интерфейсов, поэтому как делается в любом не подскажу. Я пользуюсь Sourcetree, по мне так он лучший под Windows / Mac. Но в общем могу и ошибаться.

А что не так с консолью? :)

**Comment by AlexGyver** [comment]
Ну тип зачем мне нажимать 500 кнопок на клавиатуре, если можно нажать одну на мышке?) Я пользуюсь git desctop
 Итак, достаточно ли сделать просто одну папку с прошивкой и всё? Обновлять тупо в неё и не думать о совместимости и версиях?)

**Comment by Nalorokk** [comment]
Ну в общем да, о версиях и совместимости как раз git думает :) В это то и фишка

**Comment by AlexGyver** [comment]
Принял, будет одна папка и одна мамка
