### ISSUE TITLE
update code

### ISSUE THREAD

**Issue by Svet98** [AlexGyver/GyverLamp2#15]
Обновите пожалуйста исходники.
У Вас выложены 0.2.0  а по ОТА прилетает 0.22b

Спасибо))

**Comment by GyverLibs** [comment]
Это какая то другая версия. Исходник 0.23b выложен

**Comment by Svet98** [comment]
По ссылке http://ota.alexgyver.ru/GL2_version.html
0.22b
в файле [GyverLamp2.ino](https://github.com/AlexGyver/GyverLamp2/blob/main/firmware/GyverLamp2/GyverLamp2.ino)
при открытии самая последняя вкладка - launch.json

{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  "version": "0.2.0",
  "configurations": [
    
  ]
}

Проект скачивала вчера

**Comment by GyverLibs** [comment]
Там вообще нет такого файла. И это версия intellisense, написано ведь...
